[tool.poetry]
name = "example"
version = "1.0.0"
description = "test foo bar"
authors = [" "]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "~3.12"
fastapi = {extras = ["standard"], version = "^0.115.4"}
httpx = "^0.27.2"
