---
name: Release

on:
  release:
    types:
      - published
    tags:
      - "[a-z]+-[0-9].[0-9].[0-9]"

jobs:
  stuff:
    runs-on: ubuntu-latest
    name: Stuff
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - id: parse-tagname
        run: |
          echo "service=${TAG_NAME%-*}" >> "$GITHUB_OUTPUT"
          echo "version=${TAG_NAME#*-}" >> "$GITHUB_OUTPUT"
      - name: build
        env:
          SERVICE: ${{ steps.parse-tagname.outputs.service }}
          VERSION: ${{ steps.parse-tagname.outputs.version }}
        run: |
          echo 'run docker build etc. stuff here'
          echo "service=$SERVICE"
          echo "version=$VERSION"
