---
name: Release

on:
  release:
    types:
      - published

jobs:
  application:
    if: "!contains(github.ref_name, '-')"
    runs-on: ubuntu-latest
    name: Release Application
    steps:
      - run: |
          echo "Application v${{ github.ref_name }} :tada:"

  service:
    if: contains(github.ref_name, '-')
    runs-on: ubuntu-latest
    name: Release Service
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - id: parse-tagname
        run: |
          echo "service=${TAG_NAME%-*}" >> "$GITHUB_OUTPUT"
          echo "version=${TAG_NAME#*-}" >> "$GITHUB_OUTPUT"
      - name: build
        env:
          SERVICE: ${{ steps.parse-tagname.outputs.service }}
          VERSION: ${{ steps.parse-tagname.outputs.version }}
        run: |
          echo 'run docker build etc. stuff here'
          echo "service=$SERVICE"
          echo "version=$VERSION"
