---
name: Versions Changed

on:
  push:
    branches: [main]
    # paths:
    #   - compose.yaml
    #   - ember/package.json
    #   - api/pyproject.toml
    #   - caluma/version.txt

jobs:
  check-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - name: api
            version-file: api/pyproject.toml
            command: python -c 'import sys; import tomllib; print(tomllib.loads(sys.stdin.read())["tools"]["poetry"]["version"])'
          - name: ember
            version-file: ember/package.json
            command: jq -r '.version'
          - name: caluma
            version-file: caluma/version.txt
            command: cat
          - name: mysagw
            version-file: compose.yaml
            command: yq '.x-version'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install python
        if: contains(matrix.config.version-file, 'toml')
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get new version
        id: after
        run: |
          echo "version=$(cat ${{ matrix.config.version-file }} | ${{ matrix.config.command }})" >> "$GITHUB_OUTPUT"

      - name: Get previous version
        id: before
        run: |
          echo "version=$(git show ${{ github.event.before }}:${{ matrix.config.version-file }} | ${{ matrix.config.command }})" >> "$GITHUB_OUTPUT"

      - name: Show versions
        env:
          NEW: ${{ steps.after.outputs.version }}
          OLD: ${{ steps.before.outputs.version }}
        run: |
          echo "New Version: $NEW"
          echo "Old Version: $OLD"
